services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=game-state
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgAdmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    ports:
      - "2000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  
